---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.26.0
    app.quarkus.io/commit-id: 5e7eb556a75e366537522f704921abb6489cfb65
    app.quarkus.io/vcs-uri: https://github.com/danieljscosta/quarkustestegcloud.git
    app.quarkus.io/build-timestamp: 2025-09-10 - 00:24:48 +0000
  labels:
    app.kubernetes.io/name: apipost-alomundo
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: apipost-alomundo
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: apipost-alomundo
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.26.0
    app.quarkus.io/commit-id: 5e7eb556a75e366537522f704921abb6489cfb65
    app.quarkus.io/vcs-uri: https://github.com/danieljscosta/quarkustestegcloud.git
    app.quarkus.io/build-timestamp: 2025-09-10 - 00:24:48 +0000
  labels:
    app.kubernetes.io/name: apipost-alomundo
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: apipost-alomundo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: apipost-alomundo
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.26.0
        app.quarkus.io/commit-id: 5e7eb556a75e366537522f704921abb6489cfb65
        app.quarkus.io/vcs-uri: https://github.com/danieljscosta/quarkustestegcloud.git
        app.quarkus.io/build-timestamp: 2025-09-10 - 00:24:48 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: apipost-alomundo
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/danieljscosta/apipost-alomundo:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: apipost-alomundo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
